# Generated by Django 6.1 on 2026-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_todo_deadline_date_todo_expected_duration_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='expected_duration_hours',
        ),
        migrations.AddField(
            model_name='todo',
            name='expected_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
